# Generated by Django 2.2.6 on 2019-11-06 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(default='', max_length=50)),
                ('playerMin', models.IntegerField()),
                ('playerMax', models.IntegerField()),
                ('genre', models.CharField(default='', max_length=50)),
                ('thumbnail_url', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='database.Profile')),
                ('library', models.ManyToManyField(to='database.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='database.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDateTime', models.DateTimeField()),
                ('location', models.CharField(default='The Basement', max_length=200)),
                ('attendees', models.ManyToManyField(related_name='event_attending', to='database.Profile')),
                ('eventGames', models.ManyToManyField(to='database.Game')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Profile')),
                ('pendingPlayers', models.ManyToManyField(related_name='event_invited', to='database.Profile')),
            ],
        ),
    ]
