# Generated by Django 2.2.6 on 2019-11-01 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50)),
                ('playerMin', models.IntegerField()),
                ('playerMax', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('notifications', models.CharField(max_length=1000)),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='database.Profile')),
                ('library', models.ManyToManyField(to='database.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDateTime', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='event_hosting', to='database.Profile')),
                ('eventGames', models.ManyToManyField(to='database.Game')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Profile')),
            ],
        ),
    ]
