# Generated by Django 2.2.6 on 2019-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_state',
            field=models.CharField(choices=[('PV', 'Event Setup Phase'), ('VO', 'Voting Phase'), ('AV', 'Post-Voting Phase')], default='PV', max_length=2),
        ),
    ]
