# Generated by Django 2.2.6 on 2019-11-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
        migrations.AddField(
            model_name='event',
            name='eventID',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='The Basement', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='pendingPlayers',
            field=models.ManyToManyField(related_name='event_invited', to='database.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='gameID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='event_attending', to='database.Profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('msgID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='database.Profile')),
            ],
        ),
    ]
