# Generated by Django 2.2.6 on 2019-11-12 00:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_event_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', to='database.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_hosting', to='database.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pendingPlayers',
            field=models.ManyToManyField(related_name='events_invited', to='database.Profile'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='database.Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Game')),
            ],
        ),
    ]
